export const IS_ACTIVITIES_CARD_ACTIVE = 'IS_ACTIVITIES_CARD_ACTIVE'
export const SET_ACTIVITIES_CARD_STATUS = 'SET_ACTIVITIES_CARD_STATUS'
export const TOGGLE_ACTIVITIES_CARD = 'TOGGLE_ACTIVITIES_CARD'
export const SET_ACTIVITY_NAME = 'SET_ACTIVITY_NAME'